pi@raspberrypi ~/book/code/chapter02/test $ python -m unittest -v test_Module11
test_case01 (test_Module11.TestClass12)
This is a test method. ... test_Module11.TestClass12.test_case01
FAIL

======================================================================
FAIL: test_case01 (test_Module11.TestClass12)
This is a test method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_Module11.py", line 9, in test_case01
    self.fail()
AssertionError: None

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)

