==================================================== test session starts ====================================================
platform linux2 -- Python 2.7.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/pi/book/code/chapter04/test, inifile:
collected 2 items

test_Module10.py .F

========================================================= FAILURES ==========================================================
________________________________________________________ test_case02 ________________________________________________________

    def test_case02():
        with pytest.raises(Exception):
>           x = 1 / 1
E           Failed: DID NOT RAISE

test_Module10.py:10: Failed
============================================ 1 failed, 1 passed in 0.06 seconds =============================================

